import { BrandTemplate } from "../types/brand";

export const brand_list: BrandTemplate[] = [
    {
        id: '1',
        name: 'Cerevita',
        description: 'Cereal',
        tags: [],
        image: {
            url: 'https://www.capital30.co.za/182-large_default/nestle-cerevita-corn-and-wheat-500g.jpg',
            isTransparent: false,
            incomplete: false,
            incompleteMessage: "",
            side: "front"
        },
        threeDImage: null,
        video: "",
        sizes: ['500g'],
        units: [],
        category: 'Cereal',
        addonCategories: ['toppings'],
        varieties: ['Corn and wheat', 'Corn and banana'],
        manufacturer: 'Nestlé Zimbabwe (Private) Limited',
        streetAddress: '38 Samora Machel Avenue',
        city: 'Harare',
        country: 'Zimbabwe',
        email: 'consumer.services@zw.nestle.com',
        telNumbers: [{ name: 'Consumer Services', number: '+263 242 702 393-7' }],
        website: '+263 242 702 393-7',
        draftNotes: "draft notes",
        clientEdits: [],
        reviewedAt: 12345,
        reviewNotes: "review notes example",
        reviewerId: 1,
        is_approved: false,
        createdBy: 1,
        createdAt: 12345,
        lastModified: 12345,
        ImplementationRatings: [],
        creatorClientId: 1234,
        creatorClientProductId: null,
        fromClientCleanedBy: null,
        hasZeroDepositOrder: false,
        hasTransparencyAll: false,
        isNotForUnder18: false,
        isDirty: true,
        inReview: false,
        draftType: '',
        draftCreatedAt: 0

    }, {
        id: '2',
        name: 'Mazoe',
        description: 'Juice',
        tags: [],
        image: {
            url: 'https://shop.schweppes.co.zw/221-large_default/mazoe-orange-crush-2-litre-x-6.jpg',
            isTransparent: false,
            incomplete: false,
            incompleteMessage: "",
            side: "front"
        },
        video: '',
        threeDImage: null,
        sizes: ['1L', '2L'],
        units: [],
        category: 'Beverage',
        addonCategories: ['toppings'],
        varieties: ['Orange crush', 'Blackberrry'],
        manufacturer: 'Schweppes',
        streetAddress: '67a Woolwich Road, Willovale',
        city: 'Harare',
        country: 'Zimbabwe',
        email: 'feedback@schweppes.co.zw',
        telNumbers: [
            { name: 'Head Office', number: '+2638688002173' },
            { name: 'Harare Beverage Centre', number: '+263 242 620232', }
        ],
        website: 'https://shop.schweppes.co.zw/',
        draftNotes: "draft notes",
        clientEdits: [],
        reviewedAt: 12345,
        reviewNotes: "reviewer notes example",
        reviewerId: 1,
        is_approved: false,
        createdBy: 1,
        createdAt: 12345,
        lastModified: 12345,
        ImplementationRatings: [],
        creatorClientId: 1234,
        creatorClientProductId: null,
        fromClientCleanedBy: null,
        hasZeroDepositOrder: false,
        hasTransparencyAll: false,
        isNotForUnder18: false,
        isDirty: true,
        inReview: false,
        draftType: '',
        draftCreatedAt: 0
    }
]